export const repos = [
    {
        "id": 645750521,
        "node_id": "R_kgDOJn1e-Q",
        "name": "findissues",
        "full_name": "anand346/findissues",
        "private": false,
        "owner": {
          "login": "anand346",
          "id": 64061582,
          "node_id": "MDQ6VXNlcjY0MDYxNTgy",
          "avatar_url": "https://avatars.githubusercontent.com/u/64061582?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/anand346",
          "html_url": "https://github.com/anand346",
          "followers_url": "https://api.github.com/users/anand346/followers",
          "following_url": "https://api.github.com/users/anand346/following{/other_user}",
          "gists_url": "https://api.github.com/users/anand346/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/anand346/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/anand346/subscriptions",
          "organizations_url": "https://api.github.com/users/anand346/orgs",
          "repos_url": "https://api.github.com/users/anand346/repos",
          "events_url": "https://api.github.com/users/anand346/events{/privacy}",
          "received_events_url": "https://api.github.com/users/anand346/received_events",
          "type": "User",
          "site_admin": false
        },
        "html_url": "https://github.com/anand346/findissues",
        "description": "FindIssues aims to provide you access to the most recent created issues on github which is not assigned to anyone yet, with its advance search technique 🧑‍💻✨.",
        "fork": false,
        "url": "https://api.github.com/repos/anand346/findissues",
        "forks_url": "https://api.github.com/repos/anand346/findissues/forks",
        "keys_url": "https://api.github.com/repos/anand346/findissues/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/anand346/findissues/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/anand346/findissues/teams",
        "hooks_url": "https://api.github.com/repos/anand346/findissues/hooks",
        "issue_events_url": "https://api.github.com/repos/anand346/findissues/issues/events{/number}",
        "events_url": "https://api.github.com/repos/anand346/findissues/events",
        "assignees_url": "https://api.github.com/repos/anand346/findissues/assignees{/user}",
        "branches_url": "https://api.github.com/repos/anand346/findissues/branches{/branch}",
        "tags_url": "https://api.github.com/repos/anand346/findissues/tags",
        "blobs_url": "https://api.github.com/repos/anand346/findissues/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/anand346/findissues/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/anand346/findissues/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/anand346/findissues/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/anand346/findissues/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/anand346/findissues/languages",
        "stargazers_url": "https://api.github.com/repos/anand346/findissues/stargazers",
        "contributors_url": "https://api.github.com/repos/anand346/findissues/contributors",
        "subscribers_url": "https://api.github.com/repos/anand346/findissues/subscribers",
        "subscription_url": "https://api.github.com/repos/anand346/findissues/subscription",
        "commits_url": "https://api.github.com/repos/anand346/findissues/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/anand346/findissues/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/anand346/findissues/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/anand346/findissues/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/anand346/findissues/contents/{+path}",
        "compare_url": "https://api.github.com/repos/anand346/findissues/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/anand346/findissues/merges",
        "archive_url": "https://api.github.com/repos/anand346/findissues/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/anand346/findissues/downloads",
        "issues_url": "https://api.github.com/repos/anand346/findissues/issues{/number}",
        "pulls_url": "https://api.github.com/repos/anand346/findissues/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/anand346/findissues/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/anand346/findissues/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/anand346/findissues/labels{/name}",
        "releases_url": "https://api.github.com/repos/anand346/findissues/releases{/id}",
        "deployments_url": "https://api.github.com/repos/anand346/findissues/deployments",
        "created_at": "2023-05-26T10:56:37Z",
        "updated_at": "2023-10-09T14:25:13Z",
        "pushed_at": "2023-10-10T08:45:21Z",
        "git_url": "git://github.com/anand346/findissues.git",
        "ssh_url": "git@github.com:anand346/findissues.git",
        "clone_url": "https://github.com/anand346/findissues.git",
        "svn_url": "https://github.com/anand346/findissues",
        "homepage": "https://findissues.me",
        "size": 1364,
        "stargazers_count": 24,
        "watchers_count": 24,
        "language": "JavaScript",
        "has_issues": true,
        "has_projects": true,
        "has_downloads": true,
        "has_wiki": true,
        "has_pages": false,
        "has_discussions": false,
        "forks_count": 24,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 9,
        "license": {
          "key": "mit",
          "name": "MIT License",
          "spdx_id": "MIT",
          "url": "https://api.github.com/licenses/mit",
          "node_id": "MDc6TGljZW5zZTEz"
        },
        "allow_forking": true,
        "is_template": false,
        "web_commit_signoff_required": false,
        "topics": [
          "css",
          "hacktoberfest",
          "html",
          "javascript",
          "next",
          "nextjs",
          "nodejs",
          "open-source",
          "open-source-project",
          "react",
          "reactjs"
        ],
        "visibility": "public",
        "forks": 24,
        "open_issues": 9,
        "watchers": 24,
        "default_branch": "main",
        "temp_clone_token": null,
        "network_count": 24,
        "subscribers_count": 2
    },
    {
        "id": 645750521,
        "node_id": "R_kgDOJn1e-Q",
        "name": "findissues",
        "full_name": "anand346/findissues",
        "private": false,
        "owner": {
          "login": "anand346",
          "id": 64061582,
          "node_id": "MDQ6VXNlcjY0MDYxNTgy",
          "avatar_url": "https://avatars.githubusercontent.com/u/64061582?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/anand346",
          "html_url": "https://github.com/anand346",
          "followers_url": "https://api.github.com/users/anand346/followers",
          "following_url": "https://api.github.com/users/anand346/following{/other_user}",
          "gists_url": "https://api.github.com/users/anand346/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/anand346/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/anand346/subscriptions",
          "organizations_url": "https://api.github.com/users/anand346/orgs",
          "repos_url": "https://api.github.com/users/anand346/repos",
          "events_url": "https://api.github.com/users/anand346/events{/privacy}",
          "received_events_url": "https://api.github.com/users/anand346/received_events",
          "type": "User",
          "site_admin": false
        },
        "html_url": "https://github.com/anand346/findissues",
        "description": "FindIssues aims to provide you access to the most recent created issues on github which is not assigned to anyone yet, with its advance search technique 🧑‍💻✨.",
        "fork": false,
        "url": "https://api.github.com/repos/anand346/findissues",
        "forks_url": "https://api.github.com/repos/anand346/findissues/forks",
        "keys_url": "https://api.github.com/repos/anand346/findissues/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/anand346/findissues/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/anand346/findissues/teams",
        "hooks_url": "https://api.github.com/repos/anand346/findissues/hooks",
        "issue_events_url": "https://api.github.com/repos/anand346/findissues/issues/events{/number}",
        "events_url": "https://api.github.com/repos/anand346/findissues/events",
        "assignees_url": "https://api.github.com/repos/anand346/findissues/assignees{/user}",
        "branches_url": "https://api.github.com/repos/anand346/findissues/branches{/branch}",
        "tags_url": "https://api.github.com/repos/anand346/findissues/tags",
        "blobs_url": "https://api.github.com/repos/anand346/findissues/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/anand346/findissues/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/anand346/findissues/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/anand346/findissues/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/anand346/findissues/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/anand346/findissues/languages",
        "stargazers_url": "https://api.github.com/repos/anand346/findissues/stargazers",
        "contributors_url": "https://api.github.com/repos/anand346/findissues/contributors",
        "subscribers_url": "https://api.github.com/repos/anand346/findissues/subscribers",
        "subscription_url": "https://api.github.com/repos/anand346/findissues/subscription",
        "commits_url": "https://api.github.com/repos/anand346/findissues/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/anand346/findissues/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/anand346/findissues/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/anand346/findissues/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/anand346/findissues/contents/{+path}",
        "compare_url": "https://api.github.com/repos/anand346/findissues/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/anand346/findissues/merges",
        "archive_url": "https://api.github.com/repos/anand346/findissues/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/anand346/findissues/downloads",
        "issues_url": "https://api.github.com/repos/anand346/findissues/issues{/number}",
        "pulls_url": "https://api.github.com/repos/anand346/findissues/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/anand346/findissues/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/anand346/findissues/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/anand346/findissues/labels{/name}",
        "releases_url": "https://api.github.com/repos/anand346/findissues/releases{/id}",
        "deployments_url": "https://api.github.com/repos/anand346/findissues/deployments",
        "created_at": "2023-05-26T10:56:37Z",
        "updated_at": "2023-10-09T14:25:13Z",
        "pushed_at": "2023-10-10T08:45:21Z",
        "git_url": "git://github.com/anand346/findissues.git",
        "ssh_url": "git@github.com:anand346/findissues.git",
        "clone_url": "https://github.com/anand346/findissues.git",
        "svn_url": "https://github.com/anand346/findissues",
        "homepage": "https://findissues.me",
        "size": 1364,
        "stargazers_count": 24,
        "watchers_count": 24,
        "language": "JavaScript",
        "has_issues": true,
        "has_projects": true,
        "has_downloads": true,
        "has_wiki": true,
        "has_pages": false,
        "has_discussions": false,
        "forks_count": 24,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 9,
        "license": {
          "key": "mit",
          "name": "MIT License",
          "spdx_id": "MIT",
          "url": "https://api.github.com/licenses/mit",
          "node_id": "MDc6TGljZW5zZTEz"
        },
        "allow_forking": true,
        "is_template": false,
        "web_commit_signoff_required": false,
        "topics": [
          "css",
          "hacktoberfest",
          "html",
          "javascript",
          "next",
          "nextjs",
          "nodejs",
          "open-source",
          "open-source-project",
          "react",
          "reactjs"
        ],
        "visibility": "public",
        "forks": 24,
        "open_issues": 9,
        "watchers": 24,
        "default_branch": "main",
        "temp_clone_token": null,
        "network_count": 24,
        "subscribers_count": 2
    },
    {
        "id": 645750521,
        "node_id": "R_kgDOJn1e-Q",
        "name": "findissues",
        "full_name": "anand346/findissues",
        "private": false,
        "owner": {
          "login": "anand346",
          "id": 64061582,
          "node_id": "MDQ6VXNlcjY0MDYxNTgy",
          "avatar_url": "https://avatars.githubusercontent.com/u/64061582?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/anand346",
          "html_url": "https://github.com/anand346",
          "followers_url": "https://api.github.com/users/anand346/followers",
          "following_url": "https://api.github.com/users/anand346/following{/other_user}",
          "gists_url": "https://api.github.com/users/anand346/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/anand346/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/anand346/subscriptions",
          "organizations_url": "https://api.github.com/users/anand346/orgs",
          "repos_url": "https://api.github.com/users/anand346/repos",
          "events_url": "https://api.github.com/users/anand346/events{/privacy}",
          "received_events_url": "https://api.github.com/users/anand346/received_events",
          "type": "User",
          "site_admin": false
        },
        "html_url": "https://github.com/anand346/findissues",
        "description": "FindIssues aims to provide you access to the most recent created issues on github which is not assigned to anyone yet, with its advance search technique 🧑‍💻✨.",
        "fork": false,
        "url": "https://api.github.com/repos/anand346/findissues",
        "forks_url": "https://api.github.com/repos/anand346/findissues/forks",
        "keys_url": "https://api.github.com/repos/anand346/findissues/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/anand346/findissues/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/anand346/findissues/teams",
        "hooks_url": "https://api.github.com/repos/anand346/findissues/hooks",
        "issue_events_url": "https://api.github.com/repos/anand346/findissues/issues/events{/number}",
        "events_url": "https://api.github.com/repos/anand346/findissues/events",
        "assignees_url": "https://api.github.com/repos/anand346/findissues/assignees{/user}",
        "branches_url": "https://api.github.com/repos/anand346/findissues/branches{/branch}",
        "tags_url": "https://api.github.com/repos/anand346/findissues/tags",
        "blobs_url": "https://api.github.com/repos/anand346/findissues/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/anand346/findissues/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/anand346/findissues/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/anand346/findissues/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/anand346/findissues/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/anand346/findissues/languages",
        "stargazers_url": "https://api.github.com/repos/anand346/findissues/stargazers",
        "contributors_url": "https://api.github.com/repos/anand346/findissues/contributors",
        "subscribers_url": "https://api.github.com/repos/anand346/findissues/subscribers",
        "subscription_url": "https://api.github.com/repos/anand346/findissues/subscription",
        "commits_url": "https://api.github.com/repos/anand346/findissues/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/anand346/findissues/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/anand346/findissues/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/anand346/findissues/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/anand346/findissues/contents/{+path}",
        "compare_url": "https://api.github.com/repos/anand346/findissues/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/anand346/findissues/merges",
        "archive_url": "https://api.github.com/repos/anand346/findissues/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/anand346/findissues/downloads",
        "issues_url": "https://api.github.com/repos/anand346/findissues/issues{/number}",
        "pulls_url": "https://api.github.com/repos/anand346/findissues/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/anand346/findissues/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/anand346/findissues/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/anand346/findissues/labels{/name}",
        "releases_url": "https://api.github.com/repos/anand346/findissues/releases{/id}",
        "deployments_url": "https://api.github.com/repos/anand346/findissues/deployments",
        "created_at": "2023-05-26T10:56:37Z",
        "updated_at": "2023-10-09T14:25:13Z",
        "pushed_at": "2023-10-10T08:45:21Z",
        "git_url": "git://github.com/anand346/findissues.git",
        "ssh_url": "git@github.com:anand346/findissues.git",
        "clone_url": "https://github.com/anand346/findissues.git",
        "svn_url": "https://github.com/anand346/findissues",
        "homepage": "https://findissues.me",
        "size": 1364,
        "stargazers_count": 24,
        "watchers_count": 24,
        "language": "JavaScript",
        "has_issues": true,
        "has_projects": true,
        "has_downloads": true,
        "has_wiki": true,
        "has_pages": false,
        "has_discussions": false,
        "forks_count": 24,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 9,
        "license": {
          "key": "mit",
          "name": "MIT License",
          "spdx_id": "MIT",
          "url": "https://api.github.com/licenses/mit",
          "node_id": "MDc6TGljZW5zZTEz"
        },
        "allow_forking": true,
        "is_template": false,
        "web_commit_signoff_required": false,
        "topics": [
          "css",
          "hacktoberfest",
          "html",
          "javascript",
          "next",
          "nextjs",
          "nodejs",
          "open-source",
          "open-source-project",
          "react",
          "reactjs"
        ],
        "visibility": "public",
        "forks": 24,
        "open_issues": 9,
        "watchers": 24,
        "default_branch": "main",
        "temp_clone_token": null,
        "network_count": 24,
        "subscribers_count": 2
      },
      {
        "id": 645750521,
        "node_id": "R_kgDOJn1e-Q",
        "name": "findissues",
        "full_name": "anand346/findissues",
        "private": false,
        "owner": {
          "login": "anand346",
          "id": 64061582,
          "node_id": "MDQ6VXNlcjY0MDYxNTgy",
          "avatar_url": "https://avatars.githubusercontent.com/u/64061582?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/anand346",
          "html_url": "https://github.com/anand346",
          "followers_url": "https://api.github.com/users/anand346/followers",
          "following_url": "https://api.github.com/users/anand346/following{/other_user}",
          "gists_url": "https://api.github.com/users/anand346/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/anand346/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/anand346/subscriptions",
          "organizations_url": "https://api.github.com/users/anand346/orgs",
          "repos_url": "https://api.github.com/users/anand346/repos",
          "events_url": "https://api.github.com/users/anand346/events{/privacy}",
          "received_events_url": "https://api.github.com/users/anand346/received_events",
          "type": "User",
          "site_admin": false
        },
        "html_url": "https://github.com/anand346/findissues",
        "description": "FindIssues aims to provide you access to the most recent created issues on github which is not assigned to anyone yet, with its advance search technique 🧑‍💻✨.",
        "fork": false,
        "url": "https://api.github.com/repos/anand346/findissues",
        "forks_url": "https://api.github.com/repos/anand346/findissues/forks",
        "keys_url": "https://api.github.com/repos/anand346/findissues/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/anand346/findissues/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/anand346/findissues/teams",
        "hooks_url": "https://api.github.com/repos/anand346/findissues/hooks",
        "issue_events_url": "https://api.github.com/repos/anand346/findissues/issues/events{/number}",
        "events_url": "https://api.github.com/repos/anand346/findissues/events",
        "assignees_url": "https://api.github.com/repos/anand346/findissues/assignees{/user}",
        "branches_url": "https://api.github.com/repos/anand346/findissues/branches{/branch}",
        "tags_url": "https://api.github.com/repos/anand346/findissues/tags",
        "blobs_url": "https://api.github.com/repos/anand346/findissues/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/anand346/findissues/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/anand346/findissues/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/anand346/findissues/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/anand346/findissues/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/anand346/findissues/languages",
        "stargazers_url": "https://api.github.com/repos/anand346/findissues/stargazers",
        "contributors_url": "https://api.github.com/repos/anand346/findissues/contributors",
        "subscribers_url": "https://api.github.com/repos/anand346/findissues/subscribers",
        "subscription_url": "https://api.github.com/repos/anand346/findissues/subscription",
        "commits_url": "https://api.github.com/repos/anand346/findissues/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/anand346/findissues/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/anand346/findissues/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/anand346/findissues/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/anand346/findissues/contents/{+path}",
        "compare_url": "https://api.github.com/repos/anand346/findissues/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/anand346/findissues/merges",
        "archive_url": "https://api.github.com/repos/anand346/findissues/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/anand346/findissues/downloads",
        "issues_url": "https://api.github.com/repos/anand346/findissues/issues{/number}",
        "pulls_url": "https://api.github.com/repos/anand346/findissues/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/anand346/findissues/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/anand346/findissues/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/anand346/findissues/labels{/name}",
        "releases_url": "https://api.github.com/repos/anand346/findissues/releases{/id}",
        "deployments_url": "https://api.github.com/repos/anand346/findissues/deployments",
        "created_at": "2023-05-26T10:56:37Z",
        "updated_at": "2023-10-09T14:25:13Z",
        "pushed_at": "2023-10-10T08:45:21Z",
        "git_url": "git://github.com/anand346/findissues.git",
        "ssh_url": "git@github.com:anand346/findissues.git",
        "clone_url": "https://github.com/anand346/findissues.git",
        "svn_url": "https://github.com/anand346/findissues",
        "homepage": "https://findissues.me",
        "size": 1364,
        "stargazers_count": 24,
        "watchers_count": 24,
        "language": "JavaScript",
        "has_issues": true,
        "has_projects": true,
        "has_downloads": true,
        "has_wiki": true,
        "has_pages": false,
        "has_discussions": false,
        "forks_count": 24,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 9,
        "license": {
          "key": "mit",
          "name": "MIT License",
          "spdx_id": "MIT",
          "url": "https://api.github.com/licenses/mit",
          "node_id": "MDc6TGljZW5zZTEz"
        },
        "allow_forking": true,
        "is_template": false,
        "web_commit_signoff_required": false,
        "topics": [
          "css",
          "hacktoberfest",
          "html",
          "javascript",
          "next",
          "nextjs",
          "nodejs",
          "open-source",
          "open-source-project",
          "react",
          "reactjs"
        ],
        "visibility": "public",
        "forks": 24,
        "open_issues": 9,
        "watchers": 24,
        "default_branch": "main",
        "temp_clone_token": null,
        "network_count": 24,
        "subscribers_count": 2
    }

]
