export const repo = {
  "id": 613046652,
  "node_id": "R_kgDOJIpZfA",
  "name": "ContactBook",
  "full_name": "SzymCode/ContactBook",
  "private": false,
  "owner": {
    "login": "SzymCode",
    "id": 107359025,
    "node_id": "U_kgDOBmYrMQ",
    "avatar_url": "https://avatars.githubusercontent.com/u/107359025?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/SzymCode",
    "html_url": "https://github.com/SzymCode",
    "followers_url": "https://api.github.com/users/SzymCode/followers",
    "following_url": "https://api.github.com/users/SzymCode/following{/other_user}",
    "gists_url": "https://api.github.com/users/SzymCode/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/SzymCode/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/SzymCode/subscriptions",
    "organizations_url": "https://api.github.com/users/SzymCode/orgs",
    "repos_url": "https://api.github.com/users/SzymCode/repos",
    "events_url": "https://api.github.com/users/SzymCode/events{/privacy}",
    "received_events_url": "https://api.github.com/users/SzymCode/received_events",
    "type": "User",
    "site_admin": false
  },
  "html_url": "https://github.com/SzymCode/ContactBook",
  "description": "This website helps to storage contacts data and share it with others. It's built from scratch by me with my own ideas.",
  "fork": false,
  "url": "https://api.github.com/repos/SzymCode/ContactBook",
  "forks_url": "https://api.github.com/repos/SzymCode/ContactBook/forks",
  "keys_url": "https://api.github.com/repos/SzymCode/ContactBook/keys{/key_id}",
  "collaborators_url": "https://api.github.com/repos/SzymCode/ContactBook/collaborators{/collaborator}",
  "teams_url": "https://api.github.com/repos/SzymCode/ContactBook/teams",
  "hooks_url": "https://api.github.com/repos/SzymCode/ContactBook/hooks",
  "issue_events_url": "https://api.github.com/repos/SzymCode/ContactBook/issues/events{/number}",
  "events_url": "https://api.github.com/repos/SzymCode/ContactBook/events",
  "assignees_url": "https://api.github.com/repos/SzymCode/ContactBook/assignees{/user}",
  "branches_url": "https://api.github.com/repos/SzymCode/ContactBook/branches{/branch}",
  "tags_url": "https://api.github.com/repos/SzymCode/ContactBook/tags",
  "blobs_url": "https://api.github.com/repos/SzymCode/ContactBook/git/blobs{/sha}",
  "git_tags_url": "https://api.github.com/repos/SzymCode/ContactBook/git/tags{/sha}",
  "git_refs_url": "https://api.github.com/repos/SzymCode/ContactBook/git/refs{/sha}",
  "trees_url": "https://api.github.com/repos/SzymCode/ContactBook/git/trees{/sha}",
  "statuses_url": "https://api.github.com/repos/SzymCode/ContactBook/statuses/{sha}",
  "languages_url": "https://api.github.com/repos/SzymCode/ContactBook/languages",
  "stargazers_url": "https://api.github.com/repos/SzymCode/ContactBook/stargazers",
  "contributors_url": "https://api.github.com/repos/SzymCode/ContactBook/contributors",
  "subscribers_url": "https://api.github.com/repos/SzymCode/ContactBook/subscribers",
  "subscription_url": "https://api.github.com/repos/SzymCode/ContactBook/subscription",
  "commits_url": "https://api.github.com/repos/SzymCode/ContactBook/commits{/sha}",
  "git_commits_url": "https://api.github.com/repos/SzymCode/ContactBook/git/commits{/sha}",
  "comments_url": "https://api.github.com/repos/SzymCode/ContactBook/comments{/number}",
  "issue_comment_url": "https://api.github.com/repos/SzymCode/ContactBook/issues/comments{/number}",
  "contents_url": "https://api.github.com/repos/SzymCode/ContactBook/contents/{+path}",
  "compare_url": "https://api.github.com/repos/SzymCode/ContactBook/compare/{base}...{head}",
  "merges_url": "https://api.github.com/repos/SzymCode/ContactBook/merges",
  "archive_url": "https://api.github.com/repos/SzymCode/ContactBook/{archive_format}{/ref}",
  "downloads_url": "https://api.github.com/repos/SzymCode/ContactBook/downloads",
  "issues_url": "https://api.github.com/repos/SzymCode/ContactBook/issues{/number}",
  "pulls_url": "https://api.github.com/repos/SzymCode/ContactBook/pulls{/number}",
  "milestones_url": "https://api.github.com/repos/SzymCode/ContactBook/milestones{/number}",
  "notifications_url": "https://api.github.com/repos/SzymCode/ContactBook/notifications{?since,all,participating}",
  "labels_url": "https://api.github.com/repos/SzymCode/ContactBook/labels{/name}",
  "releases_url": "https://api.github.com/repos/SzymCode/ContactBook/releases{/id}",
  "deployments_url": "https://api.github.com/repos/SzymCode/ContactBook/deployments",
  "created_at": "2023-03-12T18:22:46Z",
  "updated_at": "2023-05-28T13:13:36Z",
  "pushed_at": "2023-05-30T14:28:41Z",
  "git_url": "git://github.com/SzymCode/ContactBook.git",
  "ssh_url": "git@github.com:SzymCode/ContactBook.git",
  "clone_url": "https://github.com/SzymCode/ContactBook.git",
  "svn_url": "https://github.com/SzymCode/ContactBook",
  "homepage": "",
  "size": 1560,
  "stargazers_count": 3,
  "watchers_count": 3,
  "language": "TypeScript",
  "has_issues": true,
  "has_projects": true,
  "has_downloads": true,
  "has_wiki": true,
  "has_pages": false,
  "has_discussions": false,
  "forks_count": 2,
  "mirror_url": null,
  "archived": false,
  "disabled": false,
  "open_issues_count": 5,
  "license": {
    "key": "bsd-3-clause",
    "name": "BSD 3-Clause \"New\" or \"Revised\" License",
    "spdx_id": "BSD-3-Clause",
    "url": "https://api.github.com/licenses/bsd-3-clause",
    "node_id": "MDc6TGljZW5zZTU="
  },
  "allow_forking": true,
  "is_template": false,
  "web_commit_signoff_required": false,
  "topics": [
    "begginer-friendly",
    "bootstrap",
    "contactbook",
    "contacts-app",
    "contributions-welcome",
    "css3",
    "django",
    "django-rest-framework",
    "educational",
    "html5",
    "npm",
    "react",
    "sqlite"
  ],
  "visibility": "public",
  "forks": 2,
  "open_issues": 5,
  "watchers": 3,
  "default_branch": "main",
  "permissions": {
    "admin": false,
    "maintain": false,
    "push": false,
    "triage": false,
    "pull": true
  },
  "temp_clone_token": "",
  "network_count": 2,
  "subscribers_count": 3
}
  